# Generated by Django 5.0.3 on 2024-10-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycountries',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
